<section class="sidebar">
    <!-- Use Navigation Here -->
    <ul class="sidebar-menu">
        <!-- DIVIDER -->
        <li class="header">INSTITUTE SERVICES</li>
        <!-- END DIVIDER -->
        <li class="active"><a href="<?php echo $this->url('dashboard'); ?>">
            <i class="fa fa-feed"></i> <span>General Announcements</span></a>
        </li>
        
        <!-- DIVIDER -->
        <li class="header">STUDENT SERVICES</li>
        <!-- END DIVIDER -->
        <li><a href="#">
            <i class="fa fa-credit-card"></i> <span>Student Fees</span></a>
        </li>
        <li><a href="#">
            <i class="fa fa-book"></i> <span>Passbook Transactions</span></a>
        </li>
        
        <!-- DIVIDER -->
        <li class="header">EMPLOYEE SERVICES</li>
        <!-- END DIVIDER -->
        <li><a href="#">
            <i class="fa fa-credit-card-alt"></i> <span>Salary Loans</span></a>
        </li>
        
        <!-- DIVIDER -->
        <li class="header">ACCOUNTING SERVICES</li>
        <!-- END DIVIDER -->
        <li><a href="#">
            <i class="fa fa-bar-chart"></i> <span>Cash Transactions</span></a>
        </li>
        <li><a href="#">
            <i class="fa fa-check-square-o"></i> <span>Bills Payment</span></a>
        </li>
        
        <!-- DIVIDER -->
        <li class="header">BILLING MANAGEMENT</li>
        <!-- END DIVIDER -->
        <li><a href="#">
            <i class="fa fa-book"></i> <span>Tuition Fees</span></a>
        </li>
        <li><a href="#">
            <i class="fa fa-gear"></i> <span>Miscellaneous Fees</span></a>
        </li>         
    </ul>
</section>